### ISSUE TITLE
Argocd helm chart setting global.domain needs overriding

### ISSUE THREAD

**Issue by andrewhibbert** [vfarcic/crossplane-tutorial#15]
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L42

`global.domain` is set to argocd.example.com, this needs overriding to argocd.127.0.0.1.nip.io for the ingress to work

**Comment by vfarcic** [comment]
Right now the host is set in `server.ingress.hosts[0]` (https://github.com/vfarcic/crossplane-tutorial/blob/main/argocd/helm-values.yaml#L14). Should it be in `global.domain` as well?

**Comment by andrewhibbert** [comment]
Yes, might also be worth installing specific versions

**Comment by vfarcic** [comment]
Would you like to make a PR?
