### ISSUE TITLE
00-intro.sh open: command not found - running from nix shell

### ISSUE THREAD

**Issue by daniel-i-geoactio** [vfarcic/crossplane-tutorial#17]
`./setup/00-intro.sh: line 94: open: command not found`

Replacing `open` with `xdg-open` fixes the problem. Maybe there is an alias missing?

**Comment by vfarcic** [comment]
That's a good catch. I completely forgot that `open` does not work everywhere, at least not out of the box. I changed the scripts to output URLs instead so that people can open them any way they can.
