### ISSUE TITLE
Gist Part 3 + Video continuity issue

### ISSUE THREAD

**Issue by jason-bent** [vfarcic/crossplane-tutorial#19]
@vfarcic 

Found small continuity issue within [Gist Part 3](https://gist.github.com/vfarcic/08162d1f3f4954c1f420fae59704b629) related [video ](https://youtu.be/X7E6YfXWgvE?t=1475)

I believe we should use `sql-v2` rather than `sql-v1` with the change from `matchLabels` to use `matchControllerRef` confirmation, otherwise we are just applying the same composition as before...

```bash
#####################################
# Resource References and Selectors #
#####################################

cat examples/$HYPERSCALER-vm.yaml

cat compositions/sql-v1/$HYPERSCALER.yaml

cat compositions/sql-v2/$HYPERSCALER.yaml

# kubectl apply --filename compositions/sql-v1 # <-- Should be sql-v2
kubectl apply --filename compositions/sql-v2

kubectl delete --filename examples/$HYPERSCALER-sql-v1.yaml # <-- This is correct

kubectl get managed
```

**Comment by vfarcic** [comment]
You're right. That was a huge mistake on my part. I got sidetracked that there should be no difference in the outcome that I applied the old version. It's corrected now. Thanks a ton for letting me know.

**Comment by jason-bent** [comment]
@vfarcic 

#Correction.  

```bash
#####################################
# Resource References and Selectors #
#####################################

cat examples/$HYPERSCALER-vm.yaml

cat compositions/sql-v1/$HYPERSCALER.yaml

cat compositions/sql-v2/$HYPERSCALER.yaml

# kubectl apply --filename compositions/sql-v1 # <-- Should be sql-v2
kubectl apply --filename compositions/sql-v2

kubectl delete --filename examples/$HYPERSCALER-sql-v1.yaml # <-- This is correct

kubectl get managed
```

**Comment by vfarcic** [comment]
Oh my... I was too hasty with the changes. Now it should be fine. Thanks a ton.
