### ISSUE TITLE
Issue with azure-v1-sql example 

### ISSUE THREAD

**Issue by maroc0s** [vfarcic/crossplane-tutorial#21]
the file `azure-sql-v1.yaml`  has the wrong name for the secret I think `my-db-20240114235140-password`.   
Considering the composition in `sql-v1/azure.yaml` is referencing `my-db-password` name.

**Comment by vfarcic** [comment]
The problem is that Azure DB IDs/names need to be unique (unlike with AWS and GCP) so the setup script overwrites that file with the correct values at https://github.com/vfarcic/crossplane-tutorial/blob/main/setup/02-compositions.sh#L146. Is that what you're looking for?

**Comment by maroc0s** [comment]
I was only referring to the secrets. [https://github.com/vfarcic/crossplane-tutorial/blob/main/examples/azure-sql-v1.yaml#L5](url) because the composition reference this name [https://github.com/vfarcic/crossplane-tutorial/blob/main/compositions/sql-v1/azure.yaml#L39-L42](url)  

`my-db-password` vs `my-db-20240114235140-password` 

unless I misunderstood your examples in the book.

**Comment by vfarcic** [comment]
You're right. I mixed that example with the one that comes later (which patches the name of the secret in the composition). I just pushed changes to the repo.

Thanks a ton for discovering it and letting me know.
