### ISSUE TITLE
Error from server (NotFound): secrets "argocd-initial-admin-secret" not found

### ISSUE THREAD

**Issue by cavokz** [vfarcic/crossplane-tutorial#22]
At the end of `setup/00-intro.sh` I get these instructions:

```
In order to access the server UI you have the following options:

1. kubectl port-forward service/argocd-server -n argocd 8080:443

    and then open the browser on http://localhost:8080 and accept the certificate

2. enable ingress in the values file `server.ingress.enabled` and either
      - Add the annotation for ssl passthrough: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
      - Set the `configs.params."server.insecure"` in the values file and terminate SSL at your ingress: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts


After reaching the UI the first time you can login with username: admin and the random password generated during the installation. You can find the password by running:

kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

(You should delete the initial secret afterwards as suggested by the Getting Started Guide: https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli)
```

but when I try `kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d` I get an error:

```
$ kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
Error from server (NotFound): secrets "argocd-initial-admin-secret" not found
```

I dug in the history of `setup/00-intro.sh` and I found https://github.com/vfarcic/crossplane-tutorial/commit/bea2b0a076a16f5ac5745981c8e3a30788de3de4 which mentions password `admin123`, I tried it and it worked!

So, it looks like the instructions are not up to date or that something else is not as expected, could you double check?

**Comment by vfarcic** [comment]
The password is indeed `admin123`. I removed those instructions since, unless I'm mistaken, the tutorial is not using the UI.

**Comment by cavokz** [comment]
I suspect that the output above is actually coming from the ArgoCD installation, your instructions on how to access ArgoCD come later, at least in the paper version of your tutorial, and indeed mention the password.

Feel free to close this issue then.
